import i18next from 'i18next';

export const LANG_EN = 'en';
export const LANG_AR = 'ar';
export const SELECTED_LANG = i18next.language == LANG_AR;
export const countriesList = [
  // {
  //   name: 'United Arab Emirates',
  //   iso2: 'ae',
  //   dialCode: '971',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Bahrain',
  //   iso2: 'bh',
  //   dialCode: '973',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Oman',
  //   iso2: 'om',
  //   dialCode: '968',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Qatar',
  //   iso2: 'qa',
  //   dialCode: '974',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Saudi Arabia',
  //   iso2: 'sa',
  //   dialCode: '966',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Kuwait',
  //   iso2: 'kw',
  //   dialCode: '965',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Jordan',
  //   iso2: 'jo',
  //   dialCode: '962',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Egypt',
  //   iso2: 'eg',
  //   dialCode: '20',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Egypt',
  //   iso2: 'eg',
  //   dialCode: '20',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'United States',
  //   iso2: 'us',
  //   dialCode: '1',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Canada',
  //   iso2: 'ca',
  //   dialCode: '1',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'United Kingdom',
  //   iso2: 'gb',
  //   dialCode: '44',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Australia',
  //   iso2: 'au',
  //   dialCode: '61',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'India',
  //   iso2: 'in',
  //   dialCode: '91',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'China',
  //   iso2: 'cn',
  //   dialCode: '86',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Brazil',
  //   iso2: 'br',
  //   dialCode: '55',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Russia',
  //   iso2: 'ru',
  //   dialCode: '7',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Germany',
  //   iso2: 'de',
  //   dialCode: '49',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'France',
  //   iso2: 'fr',
  //   dialCode: '33',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Japan',
  //   iso2: 'jp',
  //   dialCode: '81',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'South Korea',
  //   iso2: 'kr',
  //   dialCode: '82',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Mexico',
  //   iso2: 'mx',
  //   dialCode: '52',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Italy',
  //   iso2: 'it',
  //   dialCode: '39',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Spain',
  //   iso2: 'es',
  //   dialCode: '34',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Nigeria',
  //   iso2: 'ng',
  //   dialCode: '234',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'South Africa',
  //   iso2: 'za',
  //   dialCode: '27',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Turkey',
  //   iso2: 'tr',
  //   dialCode: '90',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Saudi Arabia',
  //   iso2: 'sa',
  //   dialCode: '966',
  //   priority: 0,
  //   areaCodes: null,
  // },
  // {
  //   name: 'Indonesia',
  //   iso2: 'id',
  //   dialCode: '62',
  //   priority: 0,
  //   areaCodes: null,
  // },
];

export const excludedCountries = [
  // 'AF',
  // 'AX',
  // 'AL',
  // 'DZ',
  // 'AS',
  // 'AD',
  // 'AO',
  // 'AI',
  // 'AQ',
  // 'AG',
  // 'AR',
  // 'AM',
  // 'AW',
  // 'AU',
  // 'AT',
  // 'AZ',
  // 'BS',
  // 'BD',
  // 'BB',
  // 'BY',
  // 'BE',
  // 'BZ',
  // 'BJ',
  // 'BM',
  // 'BT',
  // 'BO',
  // 'BQ',
  // 'BA',
  // 'BW',
  // 'BV',
  // 'BR',
  // 'IO',
  // 'BN',
  // 'BG',
  // 'BF',
  // 'BI',
  // 'KH',
  // 'CM',
  // 'CA',
  // 'CV',
  // 'KY',
  // 'CF',
  // 'TD',
  // 'CL',
  // 'CN',
  // 'CX',
  // 'CC',
  // 'CO',
  // 'KM',
  // 'CG',
  // 'CD',
  // 'CK',
  // 'CR',
  // 'CI',
  // 'HR',
  // 'CU',
  // 'CW',
  // 'CY',
  // 'CZ',
  // 'DK',
  // 'DJ',
  // 'DM',
  // 'DO',
  // 'EC',
  // 'SV',
  // 'GQ',
  // 'ER',
  // 'EE',
  // 'ET',
  // 'FK',
  // 'FO',
  // 'FJ',
  // 'FI',
  // 'FR',
  // 'GF',
  // 'PF',
  // 'TF',
  // 'GA',
  // 'GM',
  // 'GE',
  // 'DE',
  // 'GH',
  // 'GI',
  // 'GR',
  // 'GL',
  // 'GD',
  // 'GP',
  // 'GU',
  // 'GT',
  // 'GG',
  // 'GN',
  // 'GW',
  // 'GY',
  // 'HT',
  // 'HM',
  // 'VA',
  // 'HN',
  // 'HK',
  // 'HU',
  // 'IS',
  // 'IN',
  // 'ID',
  // 'IR',
  // 'IQ',
  // 'IE',
  // 'IM',
  // 'IL',
  // 'IT',
  // 'JM',
  // 'JP',
  // 'JE',
  // 'KZ',
  // 'KE',
  // 'KI',
  // 'KP',
  // 'KR',
  // 'XK',
  // 'KG',
  // 'LA',
  // 'LV',
  // 'LB',
  // 'LS',
  // 'LR',
  // 'LY',
  // 'LI',
  // 'LT',
  // 'LU',
  // 'MO',
  // 'MK',
  // 'MG',
  // 'MW',
  // 'MY',
  // 'MV',
  // 'ML',
  // 'MT',
  // 'MH',
  // 'MQ',
  // 'MR',
  // 'MU',
  // 'YT',
  // 'MX',
  // 'FM',
  // 'MD',
  // 'MC',
  // 'MN',
  // 'ME',
  // 'MS',
  // 'MA',
  // 'MZ',
  // 'MM',
  // 'NA',
  // 'NR',
  // 'NP',
  // 'NL',
  // 'AN',
  // 'NC',
  // 'NZ',
  // 'NI',
  // 'NE',
  // 'NG',
  // 'NU',
  // 'NF',
  // 'MP',
  // 'NO',
  // 'PK',
  // 'PW',
  // 'PS',
  // 'PA',
  // 'PG',
  // 'PY',
  // 'PE',
  // 'PH',
  // 'PN',
  // 'PL',
  // 'PT',
  // 'PR',
  // 'RE',
  // 'RO',
  // 'RU',
  // 'RW',
  // 'BL',
  // 'SH',
  // 'KN',
  // 'LC',
  // 'MF',
  // 'PM',
  // 'VC',
  // 'WS',
  // 'SM',
  // 'ST',
  // 'SN',
  // 'RS',
  // 'CS',
  // 'SC',
  // 'SL',
  // 'SG',
  // 'SX',
  // 'SK',
  // 'SI',
  // 'SB',
  // 'SO',
  // 'ZA',
  // 'GS',
  // 'SS',
  // 'ES',
  // 'LK',
  // 'SD',
  // 'SR',
  // 'SJ',
  // 'SZ',
  // 'SE',
  // 'CH',
  // 'SY',
  // 'TW',
  // 'TJ',
  // 'TZ',
  // 'TH',
  // 'TL',
  // 'TG',
  // 'TK',
  // 'TO',
  // 'TT',
  // 'TN',
  // 'TR',
  // 'TM',
  // 'TC',
  // 'TV',
  // 'UG',
  // 'UA',
  // 'GB',
  // 'US',
  // 'UM',
  // 'UY',
  // 'UZ',
  // 'VU',
  // 'VE',
  // 'VN',
  // 'VG',
  // 'VI',
  // 'WF',
  // 'EH',
  // 'YE',
  // 'ZM',
  // 'ZW',
];

export const monnthsList = [
  'Jan',
  'Feb',
  'Mar',
  'Apr',
  'May',
  'Jun',
  'Jul',
  'Aug',
  'Sep',
  'Oct',
  'Nov',
  'Dec',
];

